"""Synthetic examples for the offline demo; these are NOT real job openings."""
from __future__ import annotations

SAMPLE_JOBS = [
    {
        "job_id": "demo-northstar-ai-engineer",
        "title": "Junior AI Engineer",
        "company": "Northstar Labs (SAMPLE)",
        "location": "Bengaluru, India · Remote",
        "description": "SAMPLE ROLE. Work with Python, FastAPI, retrieval-augmented generation (RAG), vector search, and evaluation pipelines. This synthetic description exists only to demonstrate skill matching.",
        "posted_at": "2 days ago (sample)",
        "schedule_type": "Full-time · Remote (sample)",
        "salary": "Not provided in sample",
        "source_name": "Synthetic demo",
        "apply_options": [],
        "apply_url": "",
        "share_url": "",
        "score": 0,
        "score_breakdown": {},
        "matched_skills": [],
        "missing_skills": [],
        "fit_reasons": [],
        "verification_status": "Demo only — not a real opening",
        "evidence_label": "Synthetic data for UI testing",
        "evidence_url": "",
        "evidence_snippet": "This is fictional sample data, not a current vacancy.",
        "is_demo": True,
    },
    {
        "job_id": "demo-nimbus-ml-engineer",
        "title": "Machine Learning Engineer — NLP",
        "company": "Nimbus Intelligence (SAMPLE)",
        "location": "Hyderabad, India",
        "description": "SAMPLE ROLE. Build NLP and machine-learning systems using Python, PyTorch, Transformers, model evaluation, and data pipelines. Experience with deploying inference APIs is useful.",
        "posted_at": "5 days ago (sample)",
        "schedule_type": "Full-time (sample)",
        "salary": "Not provided in sample",
        "source_name": "Synthetic demo",
        "apply_options": [],
        "apply_url": "",
        "share_url": "",
        "score": 0,
        "score_breakdown": {},
        "matched_skills": [],
        "missing_skills": [],
        "fit_reasons": [],
        "verification_status": "Demo only — not a real opening",
        "evidence_label": "Synthetic data for UI testing",
        "evidence_url": "",
        "evidence_snippet": "This is fictional sample data, not a current vacancy.",
        "is_demo": True,
    },
    {
        "job_id": "demo-atlas-llm-intern",
        "title": "LLM Engineer Intern",
        "company": "Atlas Systems (SAMPLE)",
        "location": "India · Remote",
        "description": "SAMPLE ROLE. Prototype LLM-powered assistants, prompt and retrieval evaluations, Python services, embeddings, and vector-database integrations. Internship position for early-career applicants.",
        "posted_at": "1 day ago (sample)",
        "schedule_type": "Internship · Remote (sample)",
        "salary": "Not provided in sample",
        "source_name": "Synthetic demo",
        "apply_options": [],
        "apply_url": "",
        "share_url": "",
        "score": 0,
        "score_breakdown": {},
        "matched_skills": [],
        "missing_skills": [],
        "fit_reasons": [],
        "verification_status": "Demo only — not a real opening",
        "evidence_label": "Synthetic data for UI testing",
        "evidence_url": "",
        "evidence_snippet": "This is fictional sample data, not a current vacancy.",
        "is_demo": True,
    },
    {
        "job_id": "demo-aster-applied-ai",
        "title": "Applied AI Engineer",
        "company": "Aster Analytics (SAMPLE)",
        "location": "Pune, India · Hybrid",
        "description": "SAMPLE ROLE. Ship internal AI workflows with Python, FastAPI, SQL, Docker, retrieval, and monitoring. The position includes quality evaluation and production reliability work.",
        "posted_at": "3 weeks ago (sample)",
        "schedule_type": "Full-time · Hybrid (sample)",
        "salary": "Not provided in sample",
        "source_name": "Synthetic demo",
        "apply_options": [],
        "apply_url": "",
        "share_url": "",
        "score": 0,
        "score_breakdown": {},
        "matched_skills": [],
        "missing_skills": [],
        "fit_reasons": [],
        "verification_status": "Demo only — not a real opening",
        "evidence_label": "Synthetic data for UI testing",
        "evidence_url": "",
        "evidence_snippet": "This is fictional sample data, not a current vacancy.",
        "is_demo": True,
    },
    {
        "job_id": "demo-vertex-platform",
        "title": "AI Platform Engineer",
        "company": "Vertex Platform Co. (SAMPLE)",
        "location": "Delhi NCR, India",
        "description": "SAMPLE ROLE. Create production Python APIs, Docker-based deployment, PostgreSQL services, Redis caching, observability, and LLM inference integrations.",
        "posted_at": "1 month ago (sample)",
        "schedule_type": "Full-time · On-site (sample)",
        "salary": "Not provided in sample",
        "source_name": "Synthetic demo",
        "apply_options": [],
        "apply_url": "",
        "share_url": "",
        "score": 0,
        "score_breakdown": {},
        "matched_skills": [],
        "missing_skills": [],
        "fit_reasons": [],
        "verification_status": "Demo only — not a real opening",
        "evidence_label": "Synthetic data for UI testing",
        "evidence_url": "",
        "evidence_snippet": "This is fictional sample data, not a current vacancy.",
        "is_demo": True,
    },
]
